### ISSUE TITLE
Permalinks need refreshing on install.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/theme-directory-env#3]
In order for pages like `getting-started` to work, permalinks need a 'save' after install.

**Comment by dd32** [comment]
Ideally the "bootstrap" functionality that's included in this env and the bootstrap in the plugin should be merged.. The plugin has an activation step that should flush the rules/etc, but i don't think it gets called properly.

https://github.com/WordPress/wordpress.org/blob/master/wordpress.org/public_html/wp-content/plugins/theme-directory/theme-directory.php#L44-L94
